apiVersion: v1
kind: PersistentVolume
metadata:
  name: bweng-postgres-pv
  namespace: bweng-database
  labels:
    app: bweng-database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/bweng-postgres"
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bweng-postgres-pvc
  namespace: bweng-database
  labels:
    app: bweng-database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 