apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bweng-database
  labels:
    app: bweng-database
    component: postgres
spec:
  selector:
    app: bweng-database
    component: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP 