apiVersion: v1
kind: ConfigMap
metadata:
  name: bweng-config
  namespace: bweng
  labels:
    app: bweng-microservices
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME_USER: "bweng_user_db"
  DB_NAME_ORDER: "bweng_order_db"
  DB_SSLMODE: "disable"
  
  # Service Configuration
  USER_SERVICE_PORT: "8080"
  ORDER_SERVICE_PORT: "8081"
  API_GATEWAY_PORT: "8082"
  GRPC_PORT: "50051"
  
  # Environment
  GIN_MODE: "release"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bweng-database-config
  namespace: bweng-database
  labels:
    app: bweng-database
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123" 