apiVersion: v1
kind: Secret
metadata:
  name: bweng-database-secret
  namespace: bweng-database
  labels:
    app: bweng-database
type: Opaque
data:
  # base64 encoded: postgres123
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: bweng-app-secret
  namespace: bweng
  labels:
    app: bweng-microservices
type: Opaque
data:
  # base64 encoded: postgres123
  DB_PASSWORD: cG9zdGdyZXMxMjM= 