apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: bweng-microservices

namespace: bweng

resources:
  # Configuration
  - config/
  
  # Storage
  - storage/
  
  # Database
  - database/
  
  # Services
  - services/
  
  # Gateway
  - gateway/
  
  # Ingress
  - ingress/

labels:
  - pairs:
      app: bweng-microservices
      version: v1.0.0
      environment: production 