apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: bweng
  labels:
    app: bweng-microservices
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bweng-microservices
      component: api-gateway
  template:
    metadata:
      labels:
        app: bweng-microservices
        component: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: bweng-api-gateway:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8082
        env:
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: bweng-config
              key: GIN_MODE
        - name: USER_SERVICE_URL
          value: "http://user-service:8080"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8081"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3 