apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service-deployment.yaml
  - user-service-service.yaml
  - order-service-deployment.yaml
  - order-service-service.yaml 