apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bweng
  labels:
    app: bweng-microservices
    component: order-service
spec:
  selector:
    app: bweng-microservices
    component: order-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP 