apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bweng
  labels:
    app: bweng-microservices
    component: user-service
spec:
  selector:
    app: bweng-microservices
    component: user-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP 